### ISSUE TITLE
Implement Visual Theme

### ISSUE THREAD

**Issue by rostag** [rostag/bigpolicy_eu#10]
## Apply colour theme and document it

UPD3: [How to find the MD color closest to your brand color](http://materialcolorize.com/convert-colors/).
UPD2: [#1239](https://github.com/angular/material2/pull/1239) & [Theming your Angular Material app](https://github.com/angular/material2/blob/master/docs/theming.md) & [Theming your custom Angular 2 components](https://github.com/angular/material2/blob/master/docs/theming-your-components.md)
UPD1: [Additional Icons](https://klarsys.github.io/angular-material-icons/)
### BigPolicy Theme Colors (Light):
- Primary: Blue Grey, A700
- Accent:  Light Green
- Warn: Red, A700 // Closest to brand's C62828
### BigPolicy Dark Theme Color:
- Dark Primary: Grey, A700
- Dark Accent:  Amber, A400, A100, A500
- Dark Warn: Deep Orange

They will be updated as we refine the design.

Material 2 Design Framework [predefined color palettes](https://www.google.com/design/spec/style/color.html):

[![image](https://cloud.githubusercontent.com/assets/451410/15798528/5ef2d804-2a33-11e6-8d38-0d633711ced9.png)](https://github.com/angular/material2/blob/master/docs/scss-theming.md)

The easy way to find the colour closest to your design is to use [this tool](http://materialcolorize.com/convert-colors/).

Our Brand Color (by logo) is #C13833
The closest Material Color is #D32F2F, which is `$md-red, A700`

**Comment by Prokop** [comment]
Кольори брати тут
https://www.google.com/design/spec/style/color.html

**Comment by Prokop** [comment]
Still pending because of 
https://github.com/rostag/bigpolicy_eu/issues/23

**Comment by Prokop** [comment]
@rostag no mentions about that in google, any ideas?

**Comment by rostag** [comment]
@Prokop -- yes, now it's possible w/out workarounds and here's officially [how-to theme angular 2 material](https://github.com/angular/material2/blob/master/docs/theming.md)

**Comment by rostag** [comment]
@Prokop — please review and merge PR #54, it implements this feature.
