### ISSUE TITLE
[UI] Футер має бути приєднаний до низу сайту але не висіти посеред екрану / The footer should be attached to the bottom of the site but not hanging in the middle of the screen

### ISSUE THREAD

**Issue by Prokop** [rostag/bigpolicy_eu#126]
<img width="1670" alt="screen shot 2017-12-25 at 2 49 27 pm" src="https://user-images.githubusercontent.com/1119396/34340078-0168efe8-e986-11e7-9e09-5be8e370190d.png">
The footer should be connected to the bottom of the screen as on all pages, examples on https://bigpolicy.eu/profile https://bigpolicy.eu/leaders https://bigpolicy.eu/projects https://bigpolicy.eu/profile
Now in the middle of the screen

**Comment by rostag** [comment]
Will be fixed!

**Comment by rostag** [comment]
Yury thanks for the fix. I'd also like to try the [flex-box](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/) based one. As soon as we use [FlexLayout](https://github.com/angular/flex-layout) we'd like to utilize it.

**Comment by Prokop** [comment]
@rostag changes are not displayed on prod

**Comment by rostag** [comment]
@Prokop 
This issue is fixed and deployed. Please verify and close if it's fixed.

**Comment by Prokop** [comment]
+
