### ISSUE TITLE
[Ui] Fixes for user pages that have images and video at the same time / Правки сторінки користувача що одночасно має відео та зображення

### ISSUE THREAD

**Issue by Prokop** [rostag/bigpolicy_eu#127]
**Requirements**
EN
- Video should not be stretched (full video, nor half of screen or etc)
- Підтримати should be shown correctly

UA
- Відео не має зжиматись (може бути на пів екрану а пів екрану місії та цілі
- Підтримати має відображатись коректно
<img width="1662" alt="screen shot 2017-12-25 at 2 57 15 pm" src="https://user-images.githubusercontent.com/1119396/34340091-29c7525e-e986-11e7-8cae-1f6b57325f64.png">

**Comment by rostag** [comment]
Fix to be deployed.

**Comment by Prokop** [comment]
@rostag а коли деплой?
