### ISSUE TITLE
[Backend] Wrong activities ads to projects of other users

### ISSUE THREAD

**Issue by vlodkoz** [rostag/bigpolicy_eu#128]
**STR**
Created leader
Created project
Created activity of project 1
>>>>
On the project 2 error happens during adding activity
On leader page during observing started to show projects with activities of other leaders. Wrong activities automatically ads to incorrect projects. (Access rights problem)

**Acceptance criterias**
We should assign activities to correct user and project and do not show them to users they not belongs to

**Comment by rostag** [comment]
Буде виправлено!

**Comment by vlodkoz** [comment]
Під фейсбук юзером заходи не додаються

**Comment by vlodkoz** [comment]
![image](https://user-images.githubusercontent.com/17308817/34454087-a96cadcc-ed6b-11e7-8ac9-c288380210f6.png)

**Comment by Prokop** [comment]
@rostag начебто фіксед а коміту не видно
