### ISSUE TITLE
Inconsistensies with packages in system-config.ts

### ISSUE THREAD

**Issue by Prokop** [rostag/bigpolicy_eu#23]
Hi, 

Upon trying to setup BigPolicy installation locally, can not navigate from splash screen to landing pages.
This problem can be seen in Console where bunsh of error has been shown:

To solve suggested:
install angular2/forms package to systep-config.ts and package.json

But mentioning these packageses raises dependency errors during npm install

So that still can not install Bigpolicy locally
Windows 8
npm3

**Comment by rostag** [comment]
Is it still actual?

**Comment by Prokop** [comment]
This problem has occurred because of miss consistencies in npm2 on Windows. We have to be with npm3 in our guide. Please note it there. @rostag 
https://www.triplet.fi/blog/npm-3-will-bring-brighter-future-for-windows-users/

**Comment by rostag** [comment]
@Prokop ok, please feel free to do it in the meantime ;)
