### ISSUE TITLE
Slug Links are not supported at all

### ISSUE THREAD

**Issue by Prokop** [rostag/bigpolicy_eu#34]
Steps to reproduce:
a) login to system and attempt to open the following link:
https://bigpolicy.eu/add-leader
Actual result:
Cannot GET /add-leader message is shown
Expected result:
Create Leader Page will appear with all elements for user creation

**Comment by rostag** [comment]
@lepta-ua -- can you please have a look onto this issue?

**Comment by rostag** [comment]
Possible solution. Will try:
http://blog.benmcmahen.com/post/41122888102/creating-slugs-for-your-blog-using-expressjs-and

**Comment by rostag** [comment]
@Prokop -- fixed in #47, please merge

**Comment by Prokop** [comment]
Hey

It works but have problems with restrictions.
I suppose when non logged user want to add project or become leader he should login first
We need implement later feature to login for not logged users.
Case:
Preconditions:
Guest user observe system and enter urls:
https://bigpolicy.eu/add-leader
https://bigpolicy.eu/add-project
Actual result:
User can see appropriate pages to link
Expected:
user need login first
did not raise new issue, let fix it here later.

**Comment by rostag** [comment]
Closing -- issue fixed.
