### ISSUE TITLE
DNS-налаштування MailGun

### ISSUE THREAD

**Issue by rostag** [rostag/bigpolicy_eu#43]
Це підзадача до задачі "Мейл-підтримка проектів" - #41

Для того, щоб ми могли розсилати листи через MailGun, треба налаштувати ДНС, як показано нижче (ще нижче -- буде текстова фотма цього ж)

![image](https://cloud.githubusercontent.com/assets/451410/19215175/b056c674-8d8e-11e6-9ccf-a598f370b47b.png)

![image](https://cloud.githubusercontent.com/assets/451410/19215166/80441694-8d8e-11e6-8326-279e1535ad70.png)

#### 2. Add DNS Records For Sending:

TXT records (known as SPF & DKIM) are required to send email through Mailgun.

Type | Hostname | Enter This Value
----- | ----- | ------------------------
TXT	| bigpolicy.eu	| v=spf1 include:mailgun.org ~all
TXT	| smtp._domainkey.bigpolicy.eu | k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDMvzQO92B8WPBehFOsm4/d8p0qmJ/oan8hMSn0vC78w9k8eRBV8qN5x7JpUE5P948HIPhs4LKC9d8j9SraR0h7L/orLtxMku9ruk9VwIpgh6iL1/Zv68iEJmsplv9w1cnfmA4fZquU0VPe2PxSPV7DEtZAvHT6cMxko4GvZdGQJQIDAQAB

#### 3. Add DNS Records For Tracking

The CNAME record is necessary for tracking opens, clicks and unsubscribes.

Type | Hostname | Enter This Value
--------- | -------------- | --------------
CNAME | email.bigpolicy.eu | mailgun.org

#### 4. Add DNS Records For Receiving (Optional)

MX records are required to receive email. Unless you already have MX records for @bigpolicy.eu pointing to another email provider (e.g. Gmail), you should update the following records.

Type | Priority | Enter This Value
------------- | -------------- | ----------
MX | 10 | mxa.mailgun.org
MX | 10 | mxb.mailgun.org

#### 5. Wait For Your Domain To Verify

Once you make the above DNS changes it can take 24-48hrs for those changes to propagate. We will email you to let you know once your domain is verified.

**Comment by Prokop** [comment]
Hi, @rostag 
thank you for detailed task
for future, in order to optimize and decrease efforts in task forwarding, you can make them more short. 

For this case, it was the same description in Mailgun settings page.

Thank you!

**Comment by rostag** [comment]
@Prokop -- thanks for fixing it quickly.

Regarding this:
>> For this case, it was the same description in Mailgun settings page.

I created a text copy after I realized you will need to manually enter this string char-by-char from screenshot of Mailgun settings page:
![image](https://cloud.githubusercontent.com/assets/451410/19219965/e0dccda8-8e19-11e6-8395-f6efaef55bae.png)

And I decided to save you few minutes ))))
:
