### ISSUE TITLE
Respect security requirements and keep it up to date

### ISSUE THREAD

**Issue by rostag** [rostag/bigpolicy_eu#49]
Check project against security requirements and do it on regular basis:
## Front-End Security

[Angular 2 Security Guidelines](https://angular.io/docs/ts/latest/guide/security.html#!#xss)
## Back-End Security

[Node.js Security Checklist](https://blog.risingstack.com/node-js-security-checklist/)
[Node.js Security Tips](https://blog.risingstack.com/node-js-security-tips/)
[Node JS Securiy Official](https://nodejs.org/en/security/)
[ExpressJS Production Best Practices: Security](https://expressjs.com/en/advanced/best-practice-security.html)
## Database Security:

[MongoDB Security Manual](https://docs.mongodb.com/manual/security/)
[MongoDB 3.2 Security Checklist](https://docs.mongodb.com/v3.2/administration/security-checklist/)
[Mongodb - Security Weaknesses in a typical NoSQL database](https://www.trustwave.com/Resources/SpiderLabs-Blog/Mongodb---Security-Weaknesses-in-a-typical-NoSQL-database/)

# Check-list:
- [ ] Prevent unauthorized access to API.
See this doc: https://auth0.com/blog/understanding-angular-2-change-detection/

# Auth0 JWT Updates (Jan 29 2018):
https://github.com/auth0-blog/nodejs-jwt-authentication-sample
https://medium.com/@blacksonic86/angular-2-authentication-revisited-611bf7373bf9
https://auth0.com/blog/real-world-angular-series-part-1/
angular2-jwt migration: https://github.com/auth0/angular2-jwt/issues/449#issuecomment-353022577

**Comment by Prokop** [comment]
@vlodkoz could be interesting and learning case for understanding IT systems and security threats

regards
