### ISSUE TITLE
Choose FE / BE frameworks and set it up

### ISSUE THREAD

**Issue by rostag** [rostag/bigpolicy_eu#6]
- [x] Angular 2 for UI + OpenShift as Platform.
- [x] Seed is original Angular 2 seed.
- [x] Integrate with seed.
- [x] dev builds.
- [x] prod builds.
- [x] Running qa- & prod- servers.
- [ ] CI on qa- & prod- servers (see local [deployment instructions](https://github.com/rostag/bigpolicy_eu/blob/develop/docs/deploy.md) for current process)

**Comment by Prokop** [comment]
@rostag 
I would like to set up continious integration on prod non prod
but I need to see how to install it locally
please update guide when possible

**Comment by rostag** [comment]
@Prokop — Doc updated. Have you got any luck with local installation?

**Comment by Prokop** [comment]
@rostag what is situation there now?

**Comment by rostag** [comment]
@Prokop 
It's got better but we need to check — maybe today in a meeting?
