### ISSUE TITLE
[LOGIC] Become leader button on the home page do not create leaders if user unlogged

### ISSUE THREAD

**Issue by Prokop** [rostag/bigpolicy_eu#65]
There is possibility to become leader directly from site landing page as for now. It should be present if:
a) there is a guest on the site
b) guest is unlogged
In case if here is a leader logged to system, this button should be removed.
![image](https://cloud.githubusercontent.com/assets/1119396/21297218/a6056be8-c584-11e6-9f4d-66620652eb1c.png)

Case 1:
Prerequisites: 
Guest user observing landing page, not logged
Steps: 
a) click on Зголошуйся в активні діячі кнопку
б) заповни форму нового діяча всі необхідні поля
в) натисни кнопку 
1 - готово
2 - як буде виглядати моя сторінка
Expected result:
Before creation new project, user will see login screen, log to the system and automatically attach newly created project to personal profile.
Actual result:
Guest user is able to go to project creation screen but upon submitting it does not get any notices, messages or possibility to create project.

Variations:
a) only logged users could create projects.
b) all could try to create project but submittion could be done only by logged users or login screen will be submitted

**Comment by rostag** [comment]
@Prokop thanks for comprehensive report, will fix!

**Comment by rostag** [comment]
@Prokop this is fixed in #82, please check on QA.

**Comment by rostag** [comment]
Як зараз виглядає реєстрація для неавторизованого лідера:

1: На стартовій він може натиснути ""
![image](https://cloud.githubusercontent.com/assets/451410/22821515/5f72c78e-ef73-11e6-9a0f-a2ea606a03c5.png)

2: І потрапить на сторінку створення лідера:
![image](https://cloud.githubusercontent.com/assets/451410/22821602/b94d0080-ef73-11e6-913c-7d97d9d69613.png)

3: Але натиснувши на "Готово" він побачить прохання авторизуватися:
![image](https://cloud.githubusercontent.com/assets/451410/22821635/e51044f2-ef73-11e6-82d3-05d8a2136388.png)

4: Після авторизації його реєстрацію завершено, дані лідера збережено:
