### ISSUE TITLE
[LOGIC] Button "Become leader" for user with projects should not be shown

### ISSUE THREAD

**Issue by Prokop** [rostag/bigpolicy_eu#66]
Prerequizites:
User is already logged into system and have some projects created.

Steps to reproduce:
Being logged as leader with projects observe buttons in top menu link
Actual result:
Button "become leader" is shown
Expected result:
Leader should not be leader again, button should not be shown to logged user with created projects

**Comment by rostag** [comment]
@Prokop this is fixed in #82, please check on QA.
