### ISSUE TITLE
[ENCH] Leader should see own projects in profile

### ISSUE THREAD

**Issue by Prokop** [rostag/bigpolicy_eu#67]
Suggest to allow to activists allow to see personal projects in the profile.

Here:
![image](https://cloud.githubusercontent.com/assets/1119396/21297350/bcbbae4a-c586-11e6-9bbb-d73eb0b6b6b2.png)
For example last floating projects sorted by date (later we can add filter) looking as Angular 2 cards

**Comment by rostag** [comment]
Good point, thanks, will be implemented!

**Comment by rostag** [comment]
Projects are shown via #79
