### ISSUE TITLE
Коли видаляється проект - його заходи потрапляють у Проект "Не на часі"

### ISSUE THREAD

**Issue by vlodkoz** [rostag/bigpolicy_eu#71]
Проект "Не на часі" — це спеціальний проект-чистилище, акумулятор відкладених заходів. 
У нього потрапляють усі заходи, які видаляються з інших проектів.
З нього захід можна видалити остаточно.

**Comment by rostag** [comment]
Почав робити як частину #91

**Comment by rostag** [comment]
Продовжив у #117
