### ISSUE TITLE
Розробити бачення, стратегію, статут/ Розпочати реєстрацію ТОВ у Глухові.

### ISSUE THREAD

**Issue by rostag** [rostag/bigpolicy_eu#9]
- [x] Бачення
- [x] Стратегія
- [x] Скелет ТЗ
- [x] Юридична документація
- [x] Статут

**Comment by vlodkoz** [comment]
Усе є у нашій папці.

**Comment by rostag** [comment]
@vlodkoz -- прошу додати ці доки прямими посиланнями прямо у цієї задачі.

**Comment by vlodkoz** [comment]
https://drive.google.com/drive/folders/0B5MpbiUSGakKamhRTndXRTQ4Sm8

**Comment by vlodkoz** [comment]
https://drive.google.com/drive/folders/0B5ujZi3oUB2OeG1QLWEwNUg3aEU
