### ISSUE TITLE
Enable localization of interface on architecture level

### ISSUE THREAD

**Issue by Prokop** [rostag/bigpolicy_eu#94]
In order to support localization approach, in the architecture should be defined way to add additional or switch languages.

For starting point there could be 2 language.

It should be defined architecture but not done year - low priority as for now.

**Comment by rostag** [comment]
Great you created this ticket. Here's the official doc on from where we can start:
https://github.com/angular/angular-cli/wiki/stories-internationalization

**Comment by Prokop** [comment]
Дублікат 113
